services:
  frontend_nginx_elias:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: frontend_nginx_elias

    restart: unless-stopped

    environment:
      - API_KEY=F1qHISGk6cwnrRea1dAaSdhevVnVTFhgLHlmaohvibN6SZ
      - API_UPSTREAM=${API_UPSTREAM:-http://host.docker.internal:8082}

    ports:
      - "8080:80"